### ISSUE TITLE
Assert malloc is non-null

### ISSUE THREAD

**Issue by ishehadeh** [nickmqb/muon#3]
I’m sorry if I’m missing something key here, just saw this project the other day and it’s very possible I’m just misunderstanding the source.

I was skimming the source of lib/memory.mu and it looks like ‘Memory.heapAllocFn’ will just abandon the program if null is returned by the system allocator. It would probably be better if the application was able to handle the failure. Most of the time it probably will just crash, but some applications can recover.

**Comment by nickmqb** [comment]
The assert is intentional; if an application wants to recover from a memory allocation failure, it is recommended that it does so via an abandonment handler. Alternatively, the program can call malloc directly if it does want to handle the result being null. Another approach would be to implement a new custom allocator that calls malloc, checks for null, and tries to resolve this situation somehow. Note that IAllocator.allocFn should never return null, as certain parts of the language (e.g. the "new" operator) rely on this. This needs to be documented better, I've filed #4 to track.

Hope that clears it up, but don't hesitate to ask if you have further questions.
